### ISSUE TITLE
rancher experimental addon only running on 2 of 3 harvester nodes

### ISSUE THREAD

**Issue by drewmullen** [harvester/experimental-addons#21]
Should i expect to see a rancher worker node on each harvester node? That is was my expectation

From harvester node:

```shell
harvester01:~ # kubectl get nodes
NAME          STATUS   ROLES                       AGE     VERSION
harvester01   Ready    control-plane,etcd,master   2d21h   v1.28.12+rke2r1
harvester02   Ready    control-plane,etcd,master   2d21h   v1.28.12+rke2r1
harvester03   Ready    control-plane,etcd,master   2d20h   v1.28.12+rke2r1
```

From Rancher: 
![image](https://github.com/user-attachments/assets/23db0857-4153-4fd6-8f68-c353e8ef2b59)

Harvester v1.3.2

**Comment by ibrokethecloud** [comment]
this is expected.

Please refer to the vcluster documentation:  https://www.vcluster.com/docs/v0.19/architecture/nodes
